== Couchbase Test Drive Manual

=== Introduction

The objective of this Test Drive is to familiarize you with the basics
of Couchbase Server in this test drive. We will also touch on
Couchbase Sync Gateway, which can extend Couchbase to the edge-- all
the way to mobile devices.  You will go through four exercises using
this test drive:

[arabic]
. Couchbase Overview
* You will log into the Couchbase https://docs.couchbase.com/server/current/manage/management-tools.html#introduction-to-couchbase-web-console[Web Console] (the web-based UI that comes
with Couchbase Server)
* Next, you will load the ``travel-sample'' bucket, a predefined data
set that’s great for experimentation.
* Finally, you will log into the https://docs.couchbase.com/sync-gateway/current/introduction.html[Sync Gateway] console briefly.
. Couchbase Core Document Operations
* You will use the Couchbase Console to add documents to a bucket.
* Next, you will locate documents using the key
* After that, you will learn how to edit documents.
* Finally, you will see how to delete a document.
. Querying JSON with SQL++
* You will read a bit about https://docs.couchbase.com/server/current/getting-started/try-a-query.html[N1QL Query]
* You will use the Couchbase Console to view indexes on the
``travel-sample'' bucket.
* Next, you will execute SELECT queries in the Query Workbench.
* Finally, you will see how to use data modification queries like
INSERT, UPDATE, and DELETE.
. Deep Searching for your Documents
* You will read a bit about https://docs.couchbase.com/server/current/fts/full-text-intro.html[Full Text Search]
* You will use the Couchbase Console to create a full text search index
* After creating the index, you will execute the FTS using search terms

=== Prerequisites

The only prerequisite is a web browser.

In this test drive, a 3 node cluster of Couchbase Server and 1 instance
of Couchbase Sync Gateway will be at your disposal.

Note that Sync Gateway is only briefly touched on in this test drive.
For more information on using Sync Gateway and the entire Couchbase
Mobile solution, please look at the xref:http://docs.couchbase.com[documentation].

=== Guide to using this test drive

The first lab needs to be done first. After that, you can elect to work
on any of the remaining labs in any order.

Code snippets and fields in JSON document will appear as a monospaced
font, like this: SELECT t.* FROM `travel-sample` t

=== What you will learn from this Test Drive

You will learn the basics of using Couchbase Server in this test drive.

Couchbase is a NoSQL, document oriented database designed for flexibility
and scale. A highly
performant key/value database engine with a memory-first architecture is
at the core of Couchbase Server. The Couchbase Console provides a
built-in UI that makes it easy to perform ops and dev tasks out of the
box. Couchbase Server also has robust querying options to match your use
cases, including https://www.couchbase.com/products/n1ql[N1QL (which is
SQL for JSON)] and a language aware full text search engine built on the
http://www.blevesearch.com/[Bleve] engine. After completing these labs,
you will understand how to use all these components.

In addition, you will also be taking a brief look at Sync
Gateway, which is part of the
https://www.couchbase.com/products/mobile[Couchbase Mobile platform].

=== Test Drive Support

If you have any questions or problems with this test drive, please
ask about on the xref:http://forums.couchbase.com/[forums].

=== Labs

These labs may be used on any cluster of Couchbase, though you probably
have arrived here by starting a cluster on Azure or GCP.

If you do not yet have a running cluster, instructions on creating a cluster
with Test Drive are here:

* link:Starting%20the%20Azure%20Test%20Drive.md[Starting
the Azure Test Drive]
* link:Starting%20the%20GCP%20Test%20Drive.md[Starting the
GCP Test Drive]

//TODO: update this with the final outline
With a cluster all ready, here are the labs we’ll work through:

* link:"Logging into Couchbase.md"[Logging into Couchbase]
* link:"Key Value Document Storage.md"[Key Value
Document Storage]
* link:"Querying with N1QL.md"[Querying with N1QL]
* link:"Full Text Search.md"[Full Text Search]

=== Key Takeaways/Summary

*Couchbase Overview*: Logging into a cluster. The Couchbase Console makes
it easy to view your cluster and perform both dev and ops tasks.

*Core Document Operations*: Documents are keys and JSON values. You
can add them quickly, find them by key, make changes by key (as long as
it’s valid JSON), and delete them by key.

*Querying JSON with SQL++*: Key/value operations will always be the fastest,
but querying multiple documents is easy with N1QL (which is just like
SQL).

*Deep Searching for your Documents*: A language-aware search for text
is another way to locate document(s). You can leverage the many full
text search options to help your users find the information they want.

xref:"Introduction Next Steps.adoc"[Next Steps…]

